FROM kathara/base

WORKDIR /app

COPY Services/HttpServer ./HttpServer
COPY Services/HttpHpot ./HttpHpot

RUN apt-get update && \
    apt-get -y install python3 python3-flask tcpflow && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
