FROM kathara/pox
LABEL org.opencontainers.image.authors="Kathara Team <contact@kathara.org>"

WORKDIR /app

COPY Services/HttpController ./HttpController

ARG DEBIAN_FRONTEND="noninteractive"
RUN pip3.9 --no-input install ryu
RUN pip3.9 --no-input install eventlet==0.30.2

RUN apt-get update && \
    apt-get -y install python3-flask python3-pip && \
    pip3 install --break-system-packages flask-socketio && \
    apt clean && \
    rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*
